# fly.toml app configuration file generated for docker-bitcoind on 2025-10-15T19:11:05-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'docker-bitcoind'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 18443
  force_https = false
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  internal_port = 18443
  protocol = "tcp"
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 18443
    force_https = false


[[mounts]]
  destination = "/root/.bitcoin"
  source = "daymarkchaindata"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  persist_root = 'always'

[metrics]
  port = 9091
  path = "/metrics" # default for most prometheus exporters